### ISSUE TITLE
Failed with Error 406

### ISSUE THREAD

**Issue by cityshrimp** [EvidentSecurity/esp-sdk-python2#1]
Exception when calling ReportsApi->list: (406)
Reason: Failed.  Response code = 406.  Response message = You must set the Accept header to application/json, or add .json to the end of your url
HTTP response headers: HTTPHeaderDict({'X-Request-Id': 'e494e367-2c13-4742-b804-8757cd5386d8', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'Vary': 'Accept-Encoding', 'Content-Length': '125', 'Server': 'nginx/1.10.3', 'X-Runtime': '0.042589', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store', 'Date': 'Thu, 13 Apr 2017 13:06:32 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {"errors":[{"status":406,"title":"You must set the Accept header to application/json, or add .json to the end of your url"}]}

**Comment by kevintyll** [comment]
The new SDKs require a new version of the API to be deployed.  We will publish the new SDKs to pypi and rubygems once the API has been updated.
